import { useEffect, useState } from 'react'
import { request } from '../../lib/api.js'
import './classroom.css'

export default function AdminTeacherAccess({ token }) {
  const [query, setQuery] = useState(''), [accounts, setAccounts] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [confirm, setConfirm] = useState(null)
  async function search(e) { e?.preventDefault(); setBusy(true); setError(''); try { const d = await request(`/api/admin/teachers?q=${encodeURIComponent(query.trim())}`, { token }); setAccounts(d.accounts) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { search() }, [token])
  async function change(account) {
    setBusy(true); setError(''); setMessage('')
    try { await request(`/api/admin/teachers/${account.account_id}`, { token, method: 'PUT', body: { active: !account.active } }); setMessage(`${account.active ? 'Removed' : 'Enabled'} teacher access for ${account.email}.`); setConfirm(null); await search() } catch (e) { setError(e.message) } finally { setBusy(false) }
  }
  return <section className="cl-admin adm-panel"><div className="adm-head"><div><p className="adm-kicker">Permissions</p><h2>Teacher access</h2></div></div><p>Teachers can sign up or enable teacher mode themselves. Use this panel to manage or restore access when needed.</p><form className="cl-row" onSubmit={search}><label className="cl-grow">Account email or username<input value={query} onChange={e => setQuery(e.target.value)} placeholder="teacher@example.com" maxLength={254}/></label><button disabled={busy}>{busy ? 'Searching…' : 'Find account'}</button></form>{error && <p role="alert" className="cl-error">{error}</p>}{message && <p role="status">{message}</p>}<div className="cl-admin-list">{accounts.map(a => <div className="cl-row" key={a.account_id}><div className="cl-grow"><strong>{a.email}</strong><small>{a.name || 'Account created'} · {a.active ? 'Teacher enabled' : 'Standard access'}{a.disabled ? ' · Account disabled' : ''}</small>{a.granted_at && <small>Granted {new Date(a.granted_at).toLocaleString()}</small>}</div>{confirm === a.account_id ? <div className="cl-row"><span>{a.active ? 'Remove access now?' : 'Approve this teacher?'}</span><button disabled={busy} onClick={() => change(a)}>{a.active ? 'Confirm removal' : 'Confirm grant'}</button><button disabled={busy} onClick={() => setConfirm(null)}>Cancel</button></div> : <button disabled={busy || (a.disabled && !a.active)} onClick={() => setConfirm(a.account_id)}>{a.active ? 'Revoke access' : 'Grant teacher access'}</button>}</div>)}</div>{!busy && !accounts.length && <p>{query ? 'No matching accounts. Check that the teacher has signed up.' : 'No teachers yet. Anyone can sign up as a teacher; you can also manage an existing account here.'}</p>}<small>Revocation takes effect on the next teacher request. Existing classes and student results are retained.</small></section>
}
