import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, GraduationCap } from 'lucide-react'
import AppHeader from '../components/AppHeader.jsx'
import CollegeInfo from '../components/CollegeInfo.jsx'
import { request } from '../lib/api.js'
import './advanced.css'

function Outlook({ data, title, rankList }) {
  return <section className="advanced-card"><span className="eyebrow">{title}</span><h2>{data.rank ? `${rankList} ${Number(data.rank).toLocaleString('en-IN')}` : 'Enter your Advanced rank'}</h2>
    {data.colleges.length ? <ul className="advanced-colleges">{data.colleges.map((c, i) => <li key={i}><h3>{c.institute}<CollegeInfo institute={c.institute} program={c.program}/></h3><p>{c.program}</p><small>{c.reference_year} · Round {c.reference_round} · {c.seat_type} · {c.gender_pool}</small><strong>{c.rank_list} closing rank {c.closing_rank.toLocaleString('en-IN')}</strong></li>)}</ul> : <p>{data.rank ? 'No matching programs in the available cutoff data for this rank and seat pool. This is not a complete admission eligibility decision.' : 'Use a JEE Advanced rank from the selected rank list. Your Main score and rank are kept separate.'}</p>}
    {data.score_references.length > 0 && <details><summary>Historical marks near this rank</summary><p>Published anchors from that year’s paper. These are references, not a marks prediction for your exam.</p>{data.score_references.map(a => <p key={a.rank}><strong>{a.marks} / {a.total_marks} marks</strong> at rank {a.rank.toLocaleString('en-IN')} · {a.year}</p>)}</details>}
  </section>
}
export default function Advanced() {
  const [form, setForm] = useState({category:'OPEN',pwd:false,female_pool:false,current_rank:'',target_rank:''})
  const [data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let active=true;request('/api/roadmap/advanced').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[])
  async function compare(e){e.preventDefault();setBusy(true);setError('');try{const params=new URLSearchParams(Object.entries(form).filter(([,v])=>v!==''));setData(await request(`/api/roadmap/advanced?${params}`))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const field=(key,value)=>setForm(f=>({...f,[key]:value}))
  return <div className="crackjee-root"><AppHeader/><main className="wrap advanced-page"><header className="advanced-heading"><div><span className="eyebrow"><GraduationCap size={16}/> JEE ADVANCED</span><h1>Your path to an IIT.</h1><p>Compare where your Advanced rank stands with the rank you’re working towards.</p></div><Link className="btn btn-secondary" to="/plan">My study plan <ArrowRight size={16}/></Link></header>
    <form className="advanced-form" onSubmit={compare}><div className="advanced-fields"><label>Rank category<select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value,current_rank:'',target_rank:''}))}>{['OPEN','EWS','OBC-NCL','SC','ST'].map(c=><option key={c}>{c}</option>)}</select></label><label>Current Advanced rank<input type="number" min="1" max="3000000" value={form.current_rank} onChange={e=>field('current_rank',e.target.value)} placeholder="Optional"/></label><label>Target Advanced rank<input type="number" min="1" max="3000000" value={form.target_rank} onChange={e=>field('target_rank',e.target.value)} placeholder="e.g. 3000"/></label><button className="btn btn-primary" disabled={busy}>{busy?'Loading…':'Compare IIT options'}</button></div><div className="advanced-checks"><label><input type="checkbox" checked={form.pwd} onChange={e=>setForm(f=>({...f,pwd:e.target.checked,current_rank:'',target_rank:''}))}/>Use the corresponding PwD rank list</label><label><input type="checkbox" checked={form.female_pool} onChange={e=>field('female_pool',e.target.checked)}/>Include female-only pools, if eligible</label></div><small>OPEN uses Advanced CRL. Reserved categories and PwD use their own Advanced rank lists. Changing the rank list clears the entered ranks.</small></form>
    {error&&<p role="alert">{error}</p>}{data&&<><div className="advanced-reference"><strong>{data.cutoff_year ? `JoSAA ${data.cutoff_year} · Round ${data.cutoff_round} · ${data.institutes} institutes`:'Reference data is not available yet'}</strong><span>Displayed comparison: {data.rank_list} · historical cutoffs, not guaranteed admissions</span></div><div className="advanced-grid"><Outlook data={data.current} title="CURRENT POSITION" rankList={data.rank_list}/><Outlook data={data.target} title="AT YOUR TARGET RANK" rankList={data.rank_list}/></div>
    <section className="advanced-card"><h2>What to work towards</h2><p>Your study milestones build accuracy, application, speed and retention. Confirm progress with Advanced-specific two-paper assessments; the Main /300 baseline in My JEE Plan does not measure Advanced readiness.</p>{data.qualification&&<p><strong>{data.qualification.year} qualifying reference:</strong> at least {data.qualification.minimum_each_subject} marks in each subject and {data.qualification.minimum_aggregate} aggregate for {data.rank_list}. Qualification and college admission are separate checks; thresholds vary by year.</p>}<p>Advanced marks references use that year’s total marks. No Main percentile conversion or fixed /300 scaling is applied here.</p><Link to="/syllabus">Explore the syllabus <ArrowRight size={14}/></Link><details><summary>Official sources & comparison limits</summary><p>Listed programs met the compared historical closing rank. Preparatory ranks are excluded. Program-specific requirements, qualification and other admission criteria still apply. Results are limited to 30 matching options.</p>{data.sources.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></p>)}</details></section></>}
  </main></div>
}
