import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Users } from 'lucide-react'
import { AssignmentCard, classApi, Empty, ErrorMessage, LoadState, Shell, useLoad } from '../components/classroom/shared.jsx'

export default function Classrooms() {
  const [params] = useSearchParams()
  const { data, loading, error, reload } = useLoad('/classrooms')
  const [code, setCode] = useState(params.get('join') || ''), [joinError, setJoinError] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [tab, setTab] = useState('active')
  async function join(e) { e.preventDefault(); setBusy(true); setJoinError(''); setMessage(''); try { const room = await classApi('/classrooms/join', { method: 'POST', body: { code } }); setMessage(`Joined ${room.name}. New tests your teacher publishes will appear here.`); setCode(''); await reload() } catch (e) { setJoinError(e.message) } finally { setBusy(false) } }
  const assignments = (data?.assignments || []).filter(a => tab === 'active' ? !['submitted', 'expired'].includes(a.status) : ['submitted', 'expired'].includes(a.status)).sort((a, b) => tab === 'active' ? new Date(a.due_at) - new Date(b.due_at) : new Date(b.due_at) - new Date(a.due_at))
  return <Shell eyebrow="YOUR CLASSROOM" title="Learn together. Move forward." intro="Tests from your teacher, with a clear next step and room to improve." action={<Link className="btn btn-secondary" to="/recommendations">My next practice <ArrowUpRight size={16}/></Link>}><div className="cl-columns"><section className="cl-main"><div className="cl-section-head"><h2>Your assignments</h2><button className="btn btn-quiet btn-sm" onClick={reload} disabled={loading}>Refresh</button></div><div className="cl-tabs" role="group" aria-label="Assignment filter"><button aria-pressed={tab === 'active'} onClick={() => setTab('active')}>To do</button><button aria-pressed={tab === 'done'} onClick={() => setTab('done')}>Completed & closed</button></div><LoadState {...{ loading, error, reload }}/>{!loading && !error && <>{assignments.length ? <div className="cl-grid">{assignments.map(a => <AssignmentCard key={a.id} assignment={a}/>)}</div> : <Empty title={tab === 'active' ? 'You’re all caught up' : 'Your work will live here'}>{tab === 'active' ? 'Join your class below, or return to your personal practice while your teacher prepares the next test.' : 'Submitted tests and released solutions appear here.'}</Empty>}</>}</section><aside className="cl-sidebar"><section className="cl-card"><span className="cl-icon"><Users size={22}/></span><h2>Join your class</h2><p>Enter the code shared by your teacher.</p><form onSubmit={join}><label>Class code<input autoComplete="off" value={code} maxLength={16} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="e.g. A7H2K9M4QP" required minLength={6}/></label><button className="btn btn-primary" disabled={busy || code.trim().length < 6}>{busy ? 'Joining…' : 'Join class'}</button></form><ErrorMessage error={joinError}/>{message && <p className="cl-success" role="status">{message}</p>}<small>You’ll receive tests published after you join.</small></section><section className="cl-card"><h3>Your classes</h3>{data?.classes.length ? data.classes.map(c => <div className="cl-class-row" key={c.id}><strong>{c.name}</strong><small>With {c.teacher}</small></div>) : <p>No classes joined yet.</p>}</section></aside></div></Shell>
}
