"""Deterministic teaching diagrams. Geometry is authored, never generated by an LLM."""
import math
from PIL import ImageDraw
from social import worker

ORANGE = '#ff8547'
WHITE = '#f6f3ee'
BLUE = '#8fc9ee'
MUTED = '#abb0b7'
TOPICS = {'Projectile range', 'Vertical throw', 'Uniform circular motion', 'Wave speed',
          'Kinetic energy scaling', 'Dilution', 'First-order half-life',
          'Odd-function integral', 'Even-function integral', 'Derivative at a point'}


def projectile_points(angle, speed=1, gravity=1):
    """Equal physical time scale for both trajectories; return world coordinates."""
    angle = math.radians(angle)
    flight = 2 * speed * math.sin(angle) / gravity
    return [(speed * math.cos(angle) * flight * i / 60,
             speed * math.sin(angle) * flight * i / 60 - gravity * (flight*i/60)**2/2)
            for i in range(61)]


def caption(content):
    return {
        'Projectile range': 'Same speed. Same landing height. No drag.',
        'Vertical throw': 'At the top: v = 0, but acceleration is still down.',
        'Uniform circular motion': 'Velocity: tangent. Acceleration: toward centre.',
        'Wave speed': 'Wave travels right; each point oscillates vertically.',
        'Kinetic energy scaling': 'Same mass: speed x3 means kinetic energy x9.',
        'Dilution': 'Adding solvent: same solute, larger total volume.',
        'First-order half-life': 'Each step halves what remains.',
        'Odd-function integral': 'Opposite signed areas cancel: integral = 0.',
        'Even-function integral': 'Equal positive areas: integrate half, then double.',
        'Derivative at a point': 'The tangent slope changes as the point moves.',
    }.get(content['topic'], '')


def arrow(draw, start, end, fill):
    draw.line((*start, *end), fill=fill, width=4)
    angle = math.atan2(end[1]-start[1], end[0]-start[0])
    draw.polygon([end, (end[0]-12*math.cos(angle-.5), end[1]-12*math.sin(angle-.5)),
                  (end[0]-12*math.cos(angle+.5), end[1]-12*math.sin(angle+.5))], fill=fill)


def draw_model(image, content, seconds):
    """Draw within x=62..642, y=355..675; model examples explicitly illustrative."""
    d = ImageDraw.Draw(image)
    topic = content['topic']
    p = min(seconds/5, 1)
    small = worker.font(20)
    def label(x, y, value, color=WHITE):
        d.text((x,y), value, font=small, fill=color)
    def ball(x,y,color=ORANGE,r=10):
        d.ellipse((x-r,y-r,x+r,y+r),fill=color)
    if topic == 'Projectile range':
        # Both tracks use one common spatial scale and one physical clock.
        d.line((95,640,610,640),fill=MUTED,width=2)
        for angle,color in [(30,ORANGE),(60,BLUE)]:
            points=projectile_points(angle)
            pix=[(100+x*570,640-y*570) for x,y in points]
            d.line(pix,fill=color,width=3)
            flight=2*math.sin(math.radians(angle))
            elapsed=min(p*2*math.sin(math.radians(60)),flight)
            x=math.cos(math.radians(angle))*elapsed
            y=math.sin(math.radians(angle))*elapsed-elapsed**2/2
            ball(100+x*570,640-y*570,color)
        label(100,370,'Illustration: 30 degrees + 60 degrees')
        label(110,595,'30 deg',ORANGE);label(380,420,'60 deg',BLUE)
    elif topic == 'Vertical throw':
        t=p*2; y=630-210*(2*t-t*t)
        d.line((220,630,220,410),fill=MUTED,width=2)
        ball(300,y)
        arrow(d,(350,y),(350,y+55),BLUE)
        label(380,y,'g downward',BLUE)
        label(100,365,'Upward speed decreases to zero, then reverses')
    elif topic == 'Uniform circular motion':
        cx,cy,r=340,520,108;a=seconds*1.3
        d.ellipse((cx-r,cy-r,cx+r,cy+r),outline=MUTED,width=3)
        x,y=cx+r*math.cos(a),cy+r*math.sin(a)
        ball(x,y);arrow(d,(x,y),(cx,cy),ORANGE)
        arrow(d,(x,y),(x-65*math.sin(a),y+65*math.cos(a)),BLUE)
        label(90,365,'Orange: acceleration     Blue: velocity')
    elif topic == 'Wave speed':
        pts=[(x,515+65*math.sin((x-90)/65-seconds*2)) for x in range(90,620)]
        d.line(pts,fill=ORANGE,width=4)
        ball(340,515+65*math.sin((340-90)/65-seconds*2),BLUE)
        arrow(d,(420,395),(590,395),WHITE);label(100,610,'Blue marker: one fixed position in the medium')
    elif topic == 'Kinetic energy scaling':
        label(95,370,'Illustration: v to 3v, same mass')
        for row,(name,factor,color) in enumerate([('K',1,BLUE),('9K',9,ORANGE)]):
            y=455+row*95;label(95,y,name,color)
            d.rectangle((160,y,160+max(1,440*factor/9*p),y+42),fill=color)
    elif topic == 'Dilution':
        level=590-175*p
        d.rectangle((235,390,465,635),outline=MUTED,width=3)
        d.rectangle((240,level,460,630),fill='#234a5b')
        for i in range(12):
            x=267+(i%4)*53;y=level+15+(i//4)*(615-level)/3
            ball(x,y,ORANGE,6)
        label(90,365,'Illustration: fixed number of solute particles')
        label(160,645,'More solvent -> lower concentration')
    elif topic == 'First-order half-life':
        step=min(int(seconds/1.5),3); count=64//(2**step)
        for i in range(64):
            ball(170+(i%16)*25,450+(i//16)*35,ORANGE if i<count else '#34383d',7)
        label(110,365,f'Half-lives elapsed: {step}');label(145,625,f'Fraction remaining: 1/{2**step}')
    elif topic in ('Odd-function integral','Even-function integral','Derivative at a point'):
        odd=topic=='Odd-function integral'; tangent=topic=='Derivative at a point'
        cx,cy,sx,sy=350,530,230,100
        d.line((95,cy,610,cy),fill=MUTED,width=2);d.line((cx,390,cx,650),fill=MUTED,width=2)
        fn=(lambda x:x**3) if odd else (lambda x:x*x)
        coords=[(cx+sx*x,cy-sy*fn(x)) for x in [i/100 for i in range(-100,101)]]
        if not tangent:
            for sign,color in [(-1,'#29485b'),(1,'#693c29')]:
                bound=min(1,seconds/4)
                xs=[sign*bound*i/60 for i in range(61)]
                d.polygon([(cx,cy)]+[(cx+sx*x,cy-sy*fn(x)) for x in xs]+[(cx+sx*xs[-1],cy)],fill=color)
        d.line(coords,fill=ORANGE,width=4)
        if tangent:
            x=-.8+1.6*p;y=fn(x);slope=2*x
            d.line((cx+sx*(x-.3),cy-sy*(y-slope*.3),cx+sx*(x+.3),cy-sy*(y+slope*.3)),fill=BLUE,width=4)
            ball(cx+sx*x,cy-sy*y,WHITE,7)
            label(105,365,'Illustration: f(x) = x^2; tangent slope = 2x')
        else:
            label(105,365,'f(x) = x^3' if odd else 'f(x) = x^2')
            label(105,650,'-a                      0                      +a')
